<a href="https://colab.research.google.com/github/Itsuki-Hamano123/experiment_search_engine/blob/master/elmo_search_engine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import datetime
import pathlib
import os
from pprint import pprint
import pickle
import time
import numpy as np
import pandas as pd

## 形態素解析ツール用意
https://qiita.com/Fulltea/items/90f6ebe6dcceaf64eaef

In [2]:
# mecabのインストール
!apt install aptitude swig
!aptitude install mecab libmecab-dev mecab-ipadic-utf8 git make curl xz-utils file -y
!pip install mecab-python3

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  aptitude-common libcgi-fast-perl libcgi-pm-perl libclass-accessor-perl
  libcwidget3v5 libencode-locale-perl libfcgi-perl libhtml-parser-perl
  libhtml-tagset-perl libhttp-date-perl libhttp-message-perl libio-html-perl
  libio-string-perl liblwp-mediatypes-perl libparse-debianchangelog-perl
  libsigc++-2.0-0v5 libsub-name-perl libtimedate-perl liburi-perl libxapian30
  swig3.0
Suggested packages:
  aptitude-doc-en | aptitude-doc apt-xapian-index debtags tasksel
  libcwidget-dev libdata-dump-perl libhtml-template-perl libxml-simple-perl
  libwww-perl xapian-tools swig-doc swig-examples swig3.0-examples swig3.0-doc
The following NEW packages will be installed:
  aptitude aptitude-common libcgi-fast-perl libcgi-pm-perl
  libclass-accessor-perl libcwidget3v5 libencode-locale-perl libfcgi-perl
  libhtml-parser-perl libhtml-tagset-perl libhttp

In [3]:
# Neologd辞書のインストール
!git clone --depth 1 https://github.com/neologd/mecab-ipadic-neologd.git
!echo yes | mecab-ipadic-neologd/bin/install-mecab-ipadic-neologd -n -a

Cloning into 'mecab-ipadic-neologd'...
remote: Enumerating objects: 75, done.
remote: Counting objects: 100% (75/75), done.
remote: Compressing objects: 100% (74/74), done.
remote: Total 75 (delta 5), reused 54 (delta 0), pack-reused 0
Unpacking objects: 100% (75/75), done.
[install-mecab-ipadic-NEologd] : Start..
[install-mecab-ipadic-NEologd] : Check the existance of libraries
[install-mecab-ipadic-NEologd] :     find => ok
[install-mecab-ipadic-NEologd] :     sort => ok
[install-mecab-ipadic-NEologd] :     head => ok
[install-mecab-ipadic-NEologd] :     cut => ok
[install-mecab-ipadic-NEologd] :     egrep => ok
[install-mecab-ipadic-NEologd] :     mecab => ok
[install-mecab-ipadic-NEologd] :     mecab-config => ok
[install-mecab-ipadic-NEologd] :     make => ok
[install-mecab-ipadic-NEologd] :     curl => ok
[install-mecab-ipadic-NEologd] :     sed => ok
[install-mecab-ipadic-NEologd] :     cat => ok
[install-mecab-ipadic-NEologd] :     diff => ok
[install-mecab-ipadic-NEologd] :   

In [0]:
import MeCab
import subprocess

In [5]:
!ls

mecab-ipadic-neologd  sample_data


In [6]:
cmd = 'echo `mecab-config --dicdir`"/mecab-ipadic-neologd"'
neologd_path = (subprocess.Popen(cmd, stdout=subprocess.PIPE,
                           shell=True).communicate()[0]).decode('utf-8')
# Neologd辞書の設定
m_neologd = MeCab.Tagger("-d {0}".format(neologd_path))

m_neologd_sample_txt = "8月3日に放送された「中居正広の金曜日のスマイルたちへ」(TBS系)で、1日たった5分でぽっこりおなかを解消するというダイエット方法を紹介。キンタロー。のダイエットにも密着。"

print("Mecab ipadic NEologd:\n",m_neologd.parse(m_neologd_sample_txt))

Mecab ipadic NEologd:
 8月3日	名詞,固有名詞,一般,*,*,*,8月3日,ハチガツミッカ,ハチガツミッカ
に	助詞,格助詞,一般,*,*,*,に,ニ,ニ
放送	名詞,サ変接続,*,*,*,*,放送,ホウソウ,ホーソー
さ	動詞,自立,*,*,サ変・スル,未然レル接続,する,サ,サ
れ	動詞,接尾,*,*,一段,連用形,れる,レ,レ
た	助動詞,*,*,*,特殊・タ,基本形,た,タ,タ
「	記号,括弧開,*,*,*,*,「,「,「
中居正広の金曜日のスマイルたちへ	名詞,固有名詞,一般,*,*,*,中居正広の金曜日のスマイルたちへ,ナカイマサヒロノキンヨウビノスマイルタチヘ,ナカイマサヒロノキンヨービノスマイルタチヘ
」(	記号,一般,*,*,*,*,*
TBS	名詞,固有名詞,一般,*,*,*,TBS,ティービーエス,ティービーエス
系	名詞,接尾,一般,*,*,*,系,ケイ,ケイ
)	記号,一般,*,*,*,*,*
で	助動詞,*,*,*,特殊・ダ,連用形,だ,デ,デ
、	記号,読点,*,*,*,*,、,、,、
1日	名詞,固有名詞,一般,*,*,*,1日,ツイタチ,ツイタチ
たった	副詞,助詞類接続,*,*,*,*,たった,タッタ,タッタ
5分	名詞,固有名詞,一般,*,*,*,5分,ゴフン,ゴフン
で	助詞,格助詞,一般,*,*,*,で,デ,デ
ぽっこりおなか	名詞,固有名詞,一般,*,*,*,ぽっこりおなか,ポッコリオナカ,ポッコリオナカ
を	助詞,格助詞,一般,*,*,*,を,ヲ,ヲ
解消	名詞,サ変接続,*,*,*,*,解消,カイショウ,カイショー
する	動詞,自立,*,*,サ変・スル,基本形,する,スル,スル
という	助詞,格助詞,連語,*,*,*,という,トイウ,トユウ
ダイエット方法	名詞,固有名詞,一般,*,*,*,ダイエット方法,ダイエットホウホウ,ダイエットホウホー
を	助詞,格助詞,一般,*,*,*,を,ヲ,ヲ
紹介	名詞,サ変接続,*,*,*,*,紹介,ショウカイ,ショーカイ
。	記号,句点,*,*,*,*,。,。,。
キンタロー。	名詞,固有名詞,一般,*,*,*,キンタロー。,キンタロー,キンタロー
の	助詞,連体化,*,*,*,*,の,ノ,ノ
ダイエット	名詞,サ変接続,*,*,*,*,ダイエット,ダイエッ

## ELMoモデルの準備
ELMoForManyLangsを使う

In [7]:
# ELMoForManyLangsに必要なライブラリ
!pip install allennlp

     |████████████████████████████████| 7.6MB 36.4MB/s 
     |████████████████████████████████| 51kB 6.9MB/s 
     |████████████████████████████████| 133kB 58.2MB/s 
     |████████████████████████████████| 256kB 61.5MB/s 
     |████████████████████████████████| 61kB 8.0MB/s 
     |████████████████████████████████| 163kB 49.2MB/s 
     |████████████████████████████████| 5.1MB 49.1MB/s 
     |████████████████████████████████| 245kB 63.3MB/s 
     |████████████████████████████████| 204kB 54.6MB/s 
     |████████████████████████████████| 30.9MB 87kB/s 
     |████████████████████████████████| 1.0MB 49.5MB/s 
     |████████████████████████████████| 51kB 7.7MB/s 
     |████████████████████████████████| 3.2MB 46.8MB/s 
     |████████████████████████████████| 2.1MB 54.4MB/s 
     |████████████████████████████████| 92kB 13.1MB/s 
  Created wheel for overrides: filename=overrides-2.8.0-cp36-none-any.whl size=5609 sha256=82dcb1aa72fdb54940f142c1307bac3cb71164152483bd72c3578f02d8b2166b
  Stored in 

### ELMoForManyLangsを利用
https://github.com/HIT-SCIR/ELMoForManyLangs#use-elmoformanylangs-programmatically

In [8]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [9]:
cd drive/My Drive/機械学習練習/全文検索エンジン作成

/content/drive/My Drive/機械学習練習/全文検索エンジン作成


In [10]:
!ls

build			   exports
configs			   faiss-gpu-1.4.0-py36_cuda9.2.148_1.tar.bz2
datasets		   info
dist			   lib
elmoformanylangs	   mecab-ipadic-neologd
elmoformanylangs.egg-info  README.md
elmo_search_engine.ipynb   setup.py
embedding


In [11]:
# ELMoForManyLangsのセットアップ
!python setup.py install

running install
running bdist_egg
running egg_info
writing elmoformanylangs.egg-info/PKG-INFO
writing dependency_links to elmoformanylangs.egg-info/dependency_links.txt
writing requirements to elmoformanylangs.egg-info/requires.txt
writing top-level names to elmoformanylangs.egg-info/top_level.txt
reading manifest file 'elmoformanylangs.egg-info/SOURCES.txt'
writing manifest file 'elmoformanylangs.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/elmoformanylangs
copying build/lib/elmoformanylangs/frontend.py -> build/bdist.linux-x86_64/egg/elmoformanylangs
copying build/lib/elmoformanylangs/__init__.py -> build/bdist.linux-x86_64/egg/elmoformanylangs
copying build/lib/elmoformanylangs/elmo.py -> build/bdist.linux-x86_64/egg/elmoformanylangs
copying build/lib/elmoformanylangs/utils.py -> build/bdist.linux-x86_64/egg/elmoformanylangs
copying build/

In [0]:
from elmoformanylangs import Embedder

In [0]:
def time_watch(func):
    """時間計測用デコレータ関数
    
    Parameters
    -----
    func : function
        実行したい関数

    """
    import functools
    import datetime
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        start = datetime.datetime.today()
        result = func(*args, **kwargs)
        end = datetime.datetime.today()
        print("実行時間:{time}".format(time=end - start))
        return result
    return wrapper

### 日本語の事前学習済み重みのダウンロード
embeddingディレクトに格納した<br>
https://qiita.com/mkt3/items/9577b63900109ff91665


In [0]:
# モデルのディレクトリ
MODEL_DIR = './embedding/word_unit_embedding_model/'

In [15]:
!nvidia-smi

Sat Apr 11 05:19:14 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64.00    Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   34C    P8     7W /  75W |      0MiB /  7611MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  

In [16]:
# batch_sizeは環境に合わせて変更（時間帯によってcolaboratoryのGPUの性能が変わるため）
elmo_model = Embedder(MODEL_DIR, batch_size=5)

2020-04-11 05:19:27,179 INFO: word embedding size: 387179
2020-04-11 05:19:41,617 INFO: Model(
  (token_embedder): ConvTokenEmbedder(
    (word_emb_layer): EmbeddingLayer(
      (embedding): Embedding(387179, 100, padding_idx=3)
    )
    (projection): Linear(in_features=100, out_features=512, bias=True)
  )
  (encoder): ElmobiLm(
    (forward_layer_0): LstmCellWithProjection(
      (input_linearity): Linear(in_features=512, out_features=16384, bias=False)
      (state_linearity): Linear(in_features=512, out_features=16384, bias=True)
      (state_projection): Linear(in_features=4096, out_features=512, bias=False)
    )
    (backward_layer_0): LstmCellWithProjection(
      (input_linearity): Linear(in_features=512, out_features=16384, bias=False)
      (state_linearity): Linear(in_features=512, out_features=16384, bias=True)
      (state_projection): Linear(in_features=4096, out_features=512, bias=False)
    )
    (forward_layer_1): LstmCellWithProjection(
      (input_linearity): Line

### 入力文書の前処理を定義

In [0]:
def is_stop_word(pos):
    """
    品詞からストップワードか判断

    Parameters
    -----
    pos : string
        品詞

    Returns
    -----
    stop_word_flag : boolean
    """
    stop_word_list = ["助詞", "助動詞", "記号", "BOS/EOS"]
    stop_word_flag = True
    if pos in stop_word_list:
        stop_word_flag = False
    return stop_word_flag

def split_text(text):
    """
    文章をわかち書きする

    Parameters
    -----
    text : string

    Returns
    -----
    result : list of string
    """
    result = []
    node = m_neologd.parseToNode(text)
    while node:
        if is_stop_word(node.feature.split(",")[0]):
            result.append(node.surface)
        node = node.next
    return result

In [0]:
def preprocessing_documents(documents):
    """
    文書をELMo用に前処理

    Parameters
    -----
    documents : list of string

    Returns
    -----
    results : list of list of string
    """
    results = []
    # バグ対処
    m_neologd.parse('')
    for document in documents:
        result = split_text(document)
        results.append(result)
    return results

In [0]:
elmo_sample_docments = ["私は犬", "犬は私", "今日の天気は雪のち晴れです"]

In [20]:
proc_documents = preprocessing_documents(elmo_sample_docments)
proc_documents

[['私', '犬'], ['犬', '私'], ['今日の天気', '雪', 'のち', '晴れ']]

### ELMoで単語の分散表現を予測

In [0]:
@time_watch
def predict_word_vec(model, proc_documents):
    """
    モデルを使い単語の分散表現を予測

    Parmeters
    -----
    model : model_obj
    proc_documents : proc_documents_obj
    
    Returns
    -----
    pred_vector : list of nparray
    """
    pred_vector = model.sents2elmo(proc_documents)
    return pred_vector

In [22]:
documnets_words_vec = predict_word_vec(elmo_model, proc_documents)

2020-04-11 05:19:48,403 INFO: 1 batches, avg len: 4.7


実行時間:0:00:00.354321


In [23]:
print(documnets_words_vec[0].shape)
print(type(documnets_words_vec[0]))
documnets_words_vec

(2, 1024)
<class 'numpy.ndarray'>


[array([[-0.3822073 , -0.39298368, -0.19943719, ..., -0.0947518 ,
          0.38196918, -0.06013573],
        [-0.99855757, -0.7653184 , -0.67188597, ...,  0.38484803,
         -0.14899619, -0.22106065]], dtype=float32),
 array([[-0.85666806, -0.24317439, -0.31542605, ..., -0.16575427,
          0.06315442, -0.31759426],
        [-0.29320082, -0.47321966, -0.83421296, ..., -0.40913573,
          0.21732388,  0.24414034]], dtype=float32),
 array([[ 0.10117573, -0.23624979,  0.00397639, ..., -0.2328723 ,
          0.17794509,  0.0607481 ],
        [-0.90098685, -0.80577874, -0.20233335, ...,  0.13288653,
          0.4778336 , -0.45927873],
        [ 1.2292985 ,  0.98217875, -0.351058  , ...,  0.05930225,
          0.5154347 , -0.4115046 ],
        [-0.65625954,  1.4385008 , -0.17021495, ..., -0.32545912,
          0.10576967,  0.18586273]], dtype=float32)]

#### 実行結果
「私は犬」と「犬は私」の２つの文章において、それぞれの文章で「私」「犬」は文章内での順番が考慮され、別々の分散表現が得られていることが分かる。

### 単語ベクトルから文書ベクトルを算出
fastTextの単語ベクトルの結合方法を参考に、文書内に含まれる単語ベクトルの平均値を文書ベクトルする<br>
[参考文献:https://arxiv.org/pdf/1607.01759.pdf](https://arxiv.org/pdf/1607.01759.pdf)

In [0]:
@time_watch
def calc_doc_vec(documnets_words_vec):
    """
    単語ベクトルから文書ベクトルを計算

    Parameters
    -----
    documents_word_vec : list of nparray

    Returns
    -----
    documents_vec : ndarray(文書数, 1つの文書内の次元数)

    Notes
    -----
    文書ベクトルの算出方法 : 文書内に含まれる全単語ベクトルの平均値
    """
    documnets_vec = []
    for document_words_vec in documnets_words_vec:
        document_vec = np.sum(document_words_vec, axis=0) / document_words_vec.shape[0]
        documnets_vec.append(document_vec)

    documnets_vec = np.array(documnets_vec)
    return documnets_vec

In [25]:
documnets_vec = calc_doc_vec(documnets_words_vec=documnets_words_vec)
documnets_vec

実行時間:0:00:00.000181


array([[-0.6903824 , -0.57915103, -0.43566158, ...,  0.14504811,
         0.1164865 , -0.1405982 ],
       [-0.5749344 , -0.35819703, -0.5748195 , ..., -0.287445  ,
         0.14023915, -0.03672696],
       [-0.05669305,  0.34466273, -0.17990749, ..., -0.09153567,
         0.31924576, -0.15604313]], dtype=float32)

In [26]:
print(documnets_vec.shape)
documnets_vec

(3, 1024)


array([[-0.6903824 , -0.57915103, -0.43566158, ...,  0.14504811,
         0.1164865 , -0.1405982 ],
       [-0.5749344 , -0.35819703, -0.5748195 , ..., -0.287445  ,
         0.14023915, -0.03672696],
       [-0.05669305,  0.34466273, -0.17990749, ..., -0.09153567,
         0.31924576, -0.15604313]], dtype=float32)

## faissのインストール
参考：https://qiita.com/SakuraDk/items/0c03b7ebd4aef8d6caed#colaboratory%E4%B8%8A%E3%81%A7%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB

In [0]:
# ダウンロードは一度のみ実行で大丈夫
#!wget https://anaconda.org/pytorch/faiss-gpu/1.4.0/download/linux-64/faiss-gpu-1.4.0-py36_cuda9.2.148_1.tar.bz2
#!tar xvjf faiss-gpu-1.4.0-py36_cuda9.2.148_1.tar.bz2

In [28]:
!cp -r lib/python3.6/site-packages/* /usr/local/lib/python3.6/dist-packages/
!pip install mkl

In [0]:
import faiss

## 検索エンジン作成

### 検索対象となるドキュメント読み込み

#### ldccデータ用の読み込み関数定義

In [0]:
def load_path_list(dir_name):
   """
   ディレクトリ配下のパス名取得
   """
   p = pathlib.Path(dir_name)
   name_list = list(p.glob("*"))
   return name_list

In [0]:
@time_watch
def load_ldcc_to_pd(dir_name):
    """
    ldccデータをDataframeに読み込み

    Parameters
    -----
    dir_name : string

    Returns
    -----
    ldcc_df : Dataframe
    """
    data_path_list = load_path_list(dir_name)
    read_message_size = 100
    
    removefile_path = pathlib.Path(DATA_DIR+'/LICENSE.txt')
    # LICENSE.txtファイルは除く
    if os.path.isfile(removefile_path):
        data_path_list.remove(removefile_path)
    print("データ件数:{size}".format(size=len(data_path_list)))

    dataset_texts = []
    for i, data_path in enumerate(data_path_list):
      with open(data_path) as f:
        # 末尾の改行コードと一部文字化けを取り除く
        data_texts = [s.rstrip().replace('\u3000','') for s in f.readlines()]
      dataset_texts.append(data_texts)
      if (i + 1) % read_message_size == 0:
        print("{i}件ファイルからテキストを読み込み完了".format(i=i+1))

    ldcc_df_columns = ['title', 'url', 'time', 'text']
    ldcc_df = pd.DataFrame(index=[], columns=ldcc_df_columns)
    for i, data_texts in enumerate(dataset_texts):
      title = data_texts[2]
      url = data_texts[0]
      time = data_texts[1]
      text = "".join(data_texts[2:])
      data_series = pd.Series([title, url, time, text], index=ldcc_df.columns)
      ldcc_df = ldcc_df.append(data_series, ignore_index=True)
      if (i + 1) % read_message_size == 0:
        print("{i}件データフレームに読み込み完了".format(i=i+1))

    ldcc_df.index = ldcc_df.index + 1
    return ldcc_df

In [32]:
DATA_DIR = "./datasets/ldcc-20140209"
file_name = "kaden-channel"

read_file_csv = "kaden-channel_20200405003708.csv"
read_bk_csv = True

if read_bk_csv:
    register_documents = pd.read_csv(DATA_DIR + '/' +  read_file_csv, index_col=0)   
else:
    register_documents = load_ldcc_to_pd(DATA_DIR + '/' + file_name)
    # csvファイルに出力
    now = datetime.datetime.now().strftime('%Y%m%d%H%M%S')
    register_documents.to_csv(DATA_DIR + '/' + file_name + '_' + now + '.csv')

register_documents.head(3)

title  ...                                               text
1  Hulu、ついに待望のApple TVに対応！一周年記念で「Hulu アンバサダープロジェク...  ...  Hulu、ついに待望のApple TVに対応！一周年記念で「Hulu アンバサダープロジェク...
2                            【ニュース】電力使用量９日が８社管内で今夏最高  ...  【ニュース】電力使用量９日が８社管内で今夏最高気温が高い日が続く。特に９日は各地で気温が上が...
3           【ガイガーカウンター特集】これなら手が届く！2万円以下の家庭用放射線計測器大集合  ...  【ガイガーカウンター特集】これなら手が届く！2万円以下の家庭用放射線計測器大集合家電チャンネ...

[3 rows x 4 columns]

### ELMoで文書ベクトルを算出

In [33]:
DATA_DIR = "./datasets/ldcc-20140209"
file_name = "kaden-channel"
TEXT_COLUMN = "text"

read_file_pickle = "kaden-channel_20200409144950.pkl"
read_bk_pickle = True

if read_bk_pickle:
    with open(DATA_DIR + '/' + read_file_pickle, 'rb') as f_pkl:
       register_documents_vec = pickle.load(f_pkl)
else:
    register_documents_words_vec = predict_word_vec(elmo_model, register_documents[TEXT_COLUMN].values)
    register_documents_vec = calc_doc_vec(register_documents_words_vec)
    # pklファイルに出力
    now = datetime.datetime.now().strftime('%Y%m%d%H%M%S')
    export_pkl_file = DATA_DIR + '/' + file_name + '_' + now + '.pkl'
    with open(export_pkl_file, mode='wb') as f:
        pickle.dump(register_documents_vec, f)

print("文書ベクトルの次元数確認{shape}".format(shape=register_documents_vec.shape))

文書ベクトルの次元数確認(864, 1024)


#### 文書ベクトルの次元圧縮（PCA）

In [0]:
@time_watch
def train_pca_model(origin_dim, after_pca_dim, vector):
    """
    基底を探索

    Parameters
    -----
    origin_dim : int
    after_pca_dim : int
    vector : np.array(n, origin_dim)

    Returns
    -----
    pca_model : pca_obj
    """
    pca_model = faiss.PCAMatrix (origin_dim, after_pca_dim)
    pca_model.train(vector)
    assert pca_model.is_trained
    return pca_model

In [125]:
register_dim = 128

PCA_MODEL = train_pca_model(origin_dim=register_documents_vec.shape[1] , after_pca_dim=register_dim,
                            vector=register_documents_vec)

実行時間:0:00:00.246024


In [0]:
@time_watch
def dimension_reduction_pca(trained_pca_model, vector):
    """
    PCAを使い次元削減実行

    Parameters
    -----
    trained_pca_model : pca_pbj
    vector : np.array(n, origin_dim)

    Returns
    -----
    proc_pca_vector : np.array(n, after_pca_dim)
    """
    proc_pca_vector = trained_pca_model.apply_py(vector)
    return proc_pca_vector

In [127]:
register_documents__pca_vec = dimension_reduction_pca(PCA_MODEL, register_documents_vec)
print("次元削減後の次元数確認：{size}".format(size=register_documents__pca_vec.shape))

実行時間:0:00:00.004241
次元削減後の次元数確認：(864, 128)


### Indexを登録する特徴量空間の定義
検索アルゴリズムと必要な初期値はこちら参照<br>
https://github.com/facebookresearch/faiss/wiki/Faiss-indexes

In [0]:
# 登録するデータ1件分の次元数
vector_dim = register_documents__pca_vec.shape[1]
# 分割する領域の数
voronoi_num = 20
# 検索時に含める近傍の領域の数
voronoi_near = 10

#### 高速な近似アルゴリズムIndeIVFFlatを使用
https://github.com/facebookresearch/faiss/wiki/Faster-search

In [0]:
quantizer = faiss.IndexFlatL2(vector_dim)
index = faiss.IndexIVFFlat(quantizer, vector_dim, voronoi_num)

### Indexへの追加（+ボロノイ領域の学習）

In [0]:
assert not index.is_trained
index.train(register_documents__pca_vec)
assert index.is_trained

In [131]:
# idの付与
ids = np.arange(start=1, stop=register_documents__pca_vec.shape[0]+1)
print("idsの長さ{size}".format(size=len(ids)))

idsの長さ864


In [0]:
index.add_with_ids(register_documents__pca_vec, ids) 

#### 結果の保存

In [0]:
EXPORT_DIR = "./exports"
now = datetime.datetime.now().strftime('%Y%m%d%H%M%S')

In [0]:
faiss.write_index(index, EXPORT_DIR + "/features_" + now + ".index")

## 検索エンジンにクエリを投げてみる

#### 質問文の前処理

In [0]:
# 質問文
queries = ["新作のカメラに関する記事", "Macの新作", "コンピュータ", "Microsoftに関する記事", "大容量の冷蔵庫", "人気な新商品","冷蔵庫欲しい、冷蔵庫欲しい、冷蔵庫欲しい"]

In [151]:
# ELMoで単語ベクトルに変換
queries_words_vec = predict_word_vec(elmo_model, queries)
# 文書ベクトルに変換
queries_vec = calc_doc_vec(queries_words_vec)

# 次元削減
queries_pca_vec = dimension_reduction_pca(PCA_MODEL, queries_vec)
print("入力の次元{shape}".format(shape=queries_pca_vec.shape))

2020-04-11 06:22:21,581 INFO: 2 batches, avg len: 12.3


実行時間:0:00:00.099555
実行時間:0:00:00.000456
実行時間:0:00:00.000283
入力の次元(7, 128)


#### インデックスから類似文を検索する

In [0]:
@time_watch
def search_doc(queries_vec, search_doc_num, index):
    """
    類似文章の検索

    Parameters
    -----
    queries_vec : ndarray
    search_doc_num : int
        何件分まで検索してくるか
    index : index_obj
        faissのindexオブジェクト

    Returns
    -----
    D : D_obj
    I : I_obj
    """
    d, i = index.search(queries_vec, search_doc_num)
    return d, i

In [155]:
# 取得したい結果の件数を設定
search_doc_num = 10

results_distances, results_ids = search_doc(queries_pca_vec, search_doc_num, index)
print(results_ids)

実行時間:0:00:00.000218
[[ 77 846 609 676 389 722 700 701 750 696]
 [298 303 299 464 308 296 236 282 467 582]
 [508 129 277 297 176 211 344 815 204 565]
 [308 236 582 465 303 464 298 296 299 467]
 [746 795 265 860 406 113  -1  -1  -1  -1]
 [831 195  38 444  75 368  34  71 232 784]
 [846  77 848 709 756 701 783 750 609 672]]


In [156]:
# 結果の描画
for i, (result_distances, result_ids) in enumerate(zip(results_distances, results_ids)):

    print("{i}番目の検索クエリ:{query}".format(i=i+1, query=queries[i]))
    print("-----検索結果-----")

    for j, (result_distance, result_id) in enumerate(zip(result_distances, result_ids)):
        if result_id != -1:
            print("第{j}位\t文書id:{id} 「{title}」 url:（{url}）"
            .format(j=j+1, id=result_id, title=register_documents["title"][result_id], url=register_documents["url"][result_id]))
            print("\t（距離{distance})\n".format(distance=result_distance))

    print("-----{i}番目の結果ここまで-----\n\n".format(i=i+1))

1番目の検索クエリ:新作のカメラに関する記事
-----検索結果-----
第1位	文書id:77 「【話題】ネット上での顔出しに抵抗ある？20代の88.4％が「抵抗ある」」 url:（http://news.livedoor.com/article/detail/5855522/）
	（距離28.359477996826172)

第2位	文書id:846 「電話？メール？SNS？ストレスなく連絡を取り合うイマドキの恋人たち【話題】」 url:（http://news.livedoor.com/article/detail/6888043/）
	（距離29.16702651977539)

第3位	文書id:609 「空前の子役ブームに衝撃？大橋のぞみ引退から見る子役の引き際とは【話題】」 url:（http://news.livedoor.com/article/detail/6342265/）
	（距離48.79570770263672)

第4位	文書id:676 「独自のフシギな世界が展開！吉高由里子のツイッターが気になる【話題】」 url:（http://news.livedoor.com/article/detail/6471550/）
	（距離51.050350189208984)

第5位	文書id:389 「嘘泣きじゃない！柳美里が北朝鮮市民の涙のワケを解説【話題】」 url:（http://news.livedoor.com/article/detail/6135885/）
	（距離51.46302795410156)

第6位	文書id:722 「逆切れ？初コメント？母親の生活保護不正受給疑惑、河本準一がツイッターのプロフィールを変更【話題】」 url:（http://news.livedoor.com/article/detail/6575659/）
	（距離52.553871154785156)

第7位	文書id:700 「視聴率が悪いのはネットのせい？テレビ関係者のコメントにネットが反論【話題】」 url:（http://news.livedoor.com/article/detail/6526530/）
	（距離52.7305908203125)

第8位	文書id:701 「お前が言うな？ミヤネ屋の塩谷報道に突っ込み殺到【話題】」