<a href="https://colab.research.google.com/github/Itsuki-Hamano123/experiment_search_engine/blob/master/elmo_search_engine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import datetime
import pathlib
import os
from pprint import pprint
import pickle
import time
import numpy as np
import pandas as pd

## 形態素解析ツール用意
https://qiita.com/Fulltea/items/90f6ebe6dcceaf64eaef

In [2]:
# mecabのインストール
!apt install aptitude swig
!aptitude install mecab libmecab-dev mecab-ipadic-utf8 git make curl xz-utils file -y
!pip install mecab-python3

Reading package lists... Done
Building dependency tree       
Reading state information... Done
aptitude is already the newest version (0.8.10-6ubuntu1).
swig is already the newest version (3.0.12-1).
0 upgraded, 0 newly installed, 0 to remove and 25 not upgraded.
mecab is already installed at the requested version (0.996-5)
libmecab-dev is already installed at the requested version (0.996-5)
mecab-ipadic-utf8 is already installed at the requested version (2.7.0-20070801+main-1)
git is already installed at the requested version (1:2.17.1-1ubuntu0.5)
make is already installed at the requested version (4.1-9.1ubuntu1)
curl is already installed at the requested version (7.58.0-2ubuntu3.8)
xz-utils is already installed at the requested version (5.2.2-1.3)
file is already installed at the requested version (1:5.32-2ubuntu0.3)
mecab is already installed at the requested version (0.996-5)
libmecab-dev is already installed at the requested version (0.996-5)
mecab-ipadic-utf8 is already install

In [3]:
# Neologd辞書のインストール
!git clone --depth 1 https://github.com/neologd/mecab-ipadic-neologd.git
!echo yes | mecab-ipadic-neologd/bin/install-mecab-ipadic-neologd -n -a

fatal: destination path 'mecab-ipadic-neologd' already exists and is not an empty directory.
[install-mecab-ipadic-NEologd] : Start..
[install-mecab-ipadic-NEologd] : Check the existance of libraries
[install-mecab-ipadic-NEologd] :     find => ok
[install-mecab-ipadic-NEologd] :     sort => ok
[install-mecab-ipadic-NEologd] :     head => ok
[install-mecab-ipadic-NEologd] :     cut => ok
[install-mecab-ipadic-NEologd] :     egrep => ok
[install-mecab-ipadic-NEologd] :     mecab => ok
[install-mecab-ipadic-NEologd] :     mecab-config => ok
[install-mecab-ipadic-NEologd] :     make => ok
[install-mecab-ipadic-NEologd] :     curl => ok
[install-mecab-ipadic-NEologd] :     sed => ok
[install-mecab-ipadic-NEologd] :     cat => ok
[install-mecab-ipadic-NEologd] :     diff => ok
[install-mecab-ipadic-NEologd] :     tar => ok
[install-mecab-ipadic-NEologd] :     unxz => ok
[install-mecab-ipadic-NEologd] :     xargs => ok
[install-mecab-ipadic-NEologd] :     grep => ok
[install-mecab-ipadic-NEo

In [0]:
import MeCab
import subprocess

In [5]:
!ls

drive  mecab-ipadic-neologd  sample_data


In [6]:
cmd = 'echo `mecab-config --dicdir`"/mecab-ipadic-neologd"'
neologd_path = (subprocess.Popen(cmd, stdout=subprocess.PIPE,
                           shell=True).communicate()[0]).decode('utf-8')
# Neologd辞書の設定
m_neologd = MeCab.Tagger("-d {0}".format(neologd_path))

m_neologd_sample_txt = "8月3日に放送された「中居正広の金曜日のスマイルたちへ」(TBS系)で、1日たった5分でぽっこりおなかを解消するというダイエット方法を紹介。キンタロー。のダイエットにも密着。"

print("Mecab ipadic NEologd:\n",m_neologd.parse(m_neologd_sample_txt))

Mecab ipadic NEologd:
 8月3日	名詞,固有名詞,一般,*,*,*,8月3日,ハチガツミッカ,ハチガツミッカ
に	助詞,格助詞,一般,*,*,*,に,ニ,ニ
放送	名詞,サ変接続,*,*,*,*,放送,ホウソウ,ホーソー
さ	動詞,自立,*,*,サ変・スル,未然レル接続,する,サ,サ
れ	動詞,接尾,*,*,一段,連用形,れる,レ,レ
た	助動詞,*,*,*,特殊・タ,基本形,た,タ,タ
「	記号,括弧開,*,*,*,*,「,「,「
中居正広の金曜日のスマイルたちへ	名詞,固有名詞,一般,*,*,*,中居正広の金曜日のスマイルたちへ,ナカイマサヒロノキンヨウビノスマイルタチヘ,ナカイマサヒロノキンヨービノスマイルタチヘ
」(	記号,一般,*,*,*,*,*
TBS	名詞,固有名詞,一般,*,*,*,TBS,ティービーエス,ティービーエス
系	名詞,接尾,一般,*,*,*,系,ケイ,ケイ
)	記号,一般,*,*,*,*,*
で	助動詞,*,*,*,特殊・ダ,連用形,だ,デ,デ
、	記号,読点,*,*,*,*,、,、,、
1日	名詞,固有名詞,一般,*,*,*,1日,ツイタチ,ツイタチ
たった	副詞,助詞類接続,*,*,*,*,たった,タッタ,タッタ
5分	名詞,固有名詞,一般,*,*,*,5分,ゴフン,ゴフン
で	助詞,格助詞,一般,*,*,*,で,デ,デ
ぽっこりおなか	名詞,固有名詞,一般,*,*,*,ぽっこりおなか,ポッコリオナカ,ポッコリオナカ
を	助詞,格助詞,一般,*,*,*,を,ヲ,ヲ
解消	名詞,サ変接続,*,*,*,*,解消,カイショウ,カイショー
する	動詞,自立,*,*,サ変・スル,基本形,する,スル,スル
という	助詞,格助詞,連語,*,*,*,という,トイウ,トユウ
ダイエット方法	名詞,固有名詞,一般,*,*,*,ダイエット方法,ダイエットホウホウ,ダイエットホウホー
を	助詞,格助詞,一般,*,*,*,を,ヲ,ヲ
紹介	名詞,サ変接続,*,*,*,*,紹介,ショウカイ,ショーカイ
。	記号,句点,*,*,*,*,。,。,。
キンタロー。	名詞,固有名詞,一般,*,*,*,キンタロー。,キンタロー,キンタロー
の	助詞,連体化,*,*,*,*,の,ノ,ノ
ダイエット	名詞,サ変接続,*,*,*,*,ダイエット,ダイエッ

## ELMoモデルの準備
ELMoForManyLangsを使う

In [7]:
# ELMoForManyLangsに必要なライブラリ
!pip install allennlp

### ELMoForManyLangsを利用
https://github.com/HIT-SCIR/ELMoForManyLangs#use-elmoformanylangs-programmatically

In [8]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [9]:
cd drive/My Drive/機械学習練習/全文検索エンジン作成

/content/drive/My Drive/機械学習練習/全文検索エンジン作成


In [10]:
!ls

build			   exports
configs			   faiss-gpu-1.4.0-py36_cuda9.2.148_1.tar.bz2
datasets		   info
dist			   lib
elmoformanylangs	   mecab-ipadic-neologd
elmoformanylangs.egg-info  README.md
elmo_search_engine.ipynb   setup.py
embedding


In [11]:
# ELMoForManyLangsのセットアップ
!python setup.py install

running install
running bdist_egg
running egg_info
writing elmoformanylangs.egg-info/PKG-INFO
writing dependency_links to elmoformanylangs.egg-info/dependency_links.txt
writing requirements to elmoformanylangs.egg-info/requires.txt
writing top-level names to elmoformanylangs.egg-info/top_level.txt
reading manifest file 'elmoformanylangs.egg-info/SOURCES.txt'
writing manifest file 'elmoformanylangs.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/elmoformanylangs
copying build/lib/elmoformanylangs/frontend.py -> build/bdist.linux-x86_64/egg/elmoformanylangs
copying build/lib/elmoformanylangs/__init__.py -> build/bdist.linux-x86_64/egg/elmoformanylangs
copying build/lib/elmoformanylangs/elmo.py -> build/bdist.linux-x86_64/egg/elmoformanylangs
copying build/lib/elmoformanylangs/utils.py -> build/bdist.linux-x86_64/egg/elmoformanylangs
copying build/

In [0]:
from elmoformanylangs import Embedder

In [0]:
def time_watch(func):
    """時間計測用デコレータ関数
    
    Parameters
    -----
    func : function
        実行したい関数

    """
    import functools
    import datetime
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        start = datetime.datetime.today()
        result = func(*args, **kwargs)
        end = datetime.datetime.today()
        print("実行時間:{time}".format(time=end - start))
        return result
    return wrapper

### 日本語の事前学習済み重みのダウンロード
embeddingディレクトに格納した<br>
https://qiita.com/mkt3/items/9577b63900109ff91665


In [0]:
# モデルのディレクトリ
MODEL_DIR = './embedding/word_unit_embedding_model/'

In [15]:
!nvidia-smi

Sun Apr  5 01:37:23 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64.00    Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P0    32W / 250W |      0MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  

In [16]:
# batch_sizeは環境に合わせて変更（時間帯によってcolaboratoryのGPUの性能が変わるため）
elmo_model = Embedder(MODEL_DIR, batch_size=5)

2020-04-05 01:37:27,328 INFO: word embedding size: 387179
2020-04-05 01:37:36,390 INFO: Model(
  (token_embedder): ConvTokenEmbedder(
    (word_emb_layer): EmbeddingLayer(
      (embedding): Embedding(387179, 100, padding_idx=3)
    )
    (projection): Linear(in_features=100, out_features=512, bias=True)
  )
  (encoder): ElmobiLm(
    (forward_layer_0): LstmCellWithProjection(
      (input_linearity): Linear(in_features=512, out_features=16384, bias=False)
      (state_linearity): Linear(in_features=512, out_features=16384, bias=True)
      (state_projection): Linear(in_features=4096, out_features=512, bias=False)
    )
    (backward_layer_0): LstmCellWithProjection(
      (input_linearity): Linear(in_features=512, out_features=16384, bias=False)
      (state_linearity): Linear(in_features=512, out_features=16384, bias=True)
      (state_projection): Linear(in_features=4096, out_features=512, bias=False)
    )
    (forward_layer_1): LstmCellWithProjection(
      (input_linearity): Line

### 入力文書の前処理を定義

In [0]:
def is_stop_word(pos):
    """
    品詞からストップワードか判断

    Parameters
    -----
    pos : string
        品詞

    Returns
    -----
    stop_word_flag : boolean
    """
    stop_word_list = ["助詞", "助動詞", "記号", "BOS/EOS"]
    stop_word_flag = True
    if pos in stop_word_list:
        stop_word_flag = False
    return stop_word_flag

def split_text(text):
    """
    文章をわかち書きする

    Parameters
    -----
    text : string

    Returns
    -----
    result : list of string
    """
    result = []
    node = m_neologd.parseToNode(text)
    while node:
        if is_stop_word(node.feature.split(",")[0]):
            result.append(node.surface)
        node = node.next
    return result

In [0]:
def preprocessing_documents(documents):
    """
    文書をELMo用に前処理

    Parameters
    -----
    documents : list of string

    Returns
    -----
    results : list of list of string
    """
    results = []
    # バグ対処
    m_neologd.parse('')
    for document in documents:
        result = split_text(document)
        results.append(result)
    return results

In [0]:
elmo_sample_docments = ["私は犬", "犬は私", "今日の天気は雪のち晴れです"]

In [20]:
proc_documents = preprocessing_documents(elmo_sample_docments)
proc_documents

[['私', '犬'], ['犬', '私'], ['今日の天気', '雪', 'のち', '晴れ']]

### ELMoで単語の分散表現を予測

In [0]:
@time_watch
def predict_word_vec(model, proc_documents):
    """
    モデルを使い単語の分散表現を予測

    Parmeters
    -----
    model : model_obj
    proc_documents : proc_documents_obj
    
    Returns
    -----
    pred_vector : list of nparray
    """
    pred_vector = model.sents2elmo(proc_documents)
    return pred_vector

In [22]:
documnets_words_vec = predict_word_vec(elmo_model, proc_documents)

2020-04-05 01:37:37,301 INFO: 1 batches, avg len: 4.7


実行時間:0:00:00.041053


In [23]:
print(documnets_words_vec[0].shape)
print(type(documnets_words_vec[0]))
documnets_words_vec

(2, 1024)
<class 'numpy.ndarray'>


[array([[-0.3822073 , -0.39298368, -0.19943719, ..., -0.0947518 ,
          0.38196918, -0.06013573],
        [-0.99855757, -0.7653184 , -0.67188597, ...,  0.38484803,
         -0.14899619, -0.22106065]], dtype=float32),
 array([[-0.85666806, -0.24317439, -0.31542605, ..., -0.16575427,
          0.06315442, -0.31759426],
        [-0.29320082, -0.47321966, -0.83421296, ..., -0.40913573,
          0.21732388,  0.24414034]], dtype=float32),
 array([[ 0.10117573, -0.23624979,  0.00397639, ..., -0.2328723 ,
          0.17794509,  0.0607481 ],
        [-0.90098685, -0.80577874, -0.20233335, ...,  0.13288653,
          0.4778336 , -0.45927873],
        [ 1.2292985 ,  0.98217875, -0.351058  , ...,  0.05930225,
          0.5154347 , -0.4115046 ],
        [-0.65625954,  1.4385008 , -0.17021495, ..., -0.32545912,
          0.10576967,  0.18586273]], dtype=float32)]

#### 実行結果
「私は犬」と「犬は私」の２つの文章において、それぞれの文章で「私」「犬」は文章内での順番が考慮され、別々の分散表現が得られていることが分かる。

### 単語ベクトルから文書ベクトルを算出
今回は簡易的に、単語ベクトルの合計値を文書ベクトルする<br>

In [0]:
@time_watch
def calc_doc_vec(documnets_words_vec):
    """
    単語ベクトルから文書ベクトルを計算

    Parameters
    -----
    documents_word_vec : list of nparray

    Returns
    -----
    documents_vec : ndarray(文書数, 1つの文書内の次元数)

    Notes
    -----
    文書ベクトルの算出方法 : 文書内に含まれる全単語ベクトルの平均値
    """
    documnets_vec = []
    for document_words_vec in documnets_words_vec:
        document_vec = np.sum(document_words_vec, axis=0) / document_words_vec.shape[0]
        documnets_vec.append(document_vec)

    documnets_vec = np.array(documnets_vec)
    return documnets_vec

In [25]:
documnets_vec = calc_doc_vec(documnets_words_vec=documnets_words_vec)
documnets_vec

実行時間:0:00:00.000643


array([[-0.6903824 , -0.57915103, -0.43566158, ...,  0.14504811,
         0.1164865 , -0.1405982 ],
       [-0.5749344 , -0.35819703, -0.5748195 , ..., -0.287445  ,
         0.14023915, -0.03672696],
       [-0.05669305,  0.34466273, -0.17990749, ..., -0.09153567,
         0.31924576, -0.15604313]], dtype=float32)

In [26]:
print(documnets_vec.shape)
documnets_vec

(3, 1024)


array([[-0.6903824 , -0.57915103, -0.43566158, ...,  0.14504811,
         0.1164865 , -0.1405982 ],
       [-0.5749344 , -0.35819703, -0.5748195 , ..., -0.287445  ,
         0.14023915, -0.03672696],
       [-0.05669305,  0.34466273, -0.17990749, ..., -0.09153567,
         0.31924576, -0.15604313]], dtype=float32)

## faissのインストール
参考：https://qiita.com/SakuraDk/items/0c03b7ebd4aef8d6caed#colaboratory%E4%B8%8A%E3%81%A7%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB

In [0]:
# ダウンロードは一度のみ実行で大丈夫
#!wget https://anaconda.org/pytorch/faiss-gpu/1.4.0/download/linux-64/faiss-gpu-1.4.0-py36_cuda9.2.148_1.tar.bz2
#!tar xvjf faiss-gpu-1.4.0-py36_cuda9.2.148_1.tar.bz2

In [28]:
!cp -r lib/python3.6/site-packages/* /usr/local/lib/python3.6/dist-packages/
!pip install mkl

In [0]:
import faiss

## 検索エンジン作成

### 検索対象となるドキュメント読み込み

#### ldccデータ用の読み込み関数定義

In [0]:
def load_path_list(dir_name):
   """
   ディレクトリ配下のパス名取得
   """
   p = pathlib.Path(dir_name)
   name_list = list(p.glob("*"))
   return name_list

In [0]:
@time_watch
def load_ldcc_to_pd(dir_name):
    """
    ldccデータをDataframeに読み込み

    Parameters
    -----
    dir_name : string

    Returns
    -----
    ldcc_df : Dataframe
    """
    data_path_list = load_path_list(dir_name)
    read_message_size = 100
    
    removefile_path = pathlib.Path(DATA_DIR+'/LICENSE.txt')
    # LICENSE.txtファイルは除く
    if os.path.isfile(removefile_path):
        data_path_list.remove(removefile_path)
    print("データ件数:{size}".format(size=len(data_path_list)))

    dataset_texts = []
    for i, data_path in enumerate(data_path_list):
      with open(data_path) as f:
        # 末尾の改行コードと一部文字化けを取り除く
        data_texts = [s.rstrip().replace('\u3000','') for s in f.readlines()]
      dataset_texts.append(data_texts)
      if (i + 1) % read_message_size == 0:
        print("{i}件ファイルからテキストを読み込み完了".format(i=i+1))

    ldcc_df_columns = ['title', 'url', 'time', 'text']
    ldcc_df = pd.DataFrame(index=[], columns=ldcc_df_columns)
    for i, data_texts in enumerate(dataset_texts):
      title = data_texts[2]
      url = data_texts[0]
      time = data_texts[1]
      text = "".join(data_texts[2:])
      data_series = pd.Series([title, url, time, text], index=ldcc_df.columns)
      ldcc_df = ldcc_df.append(data_series, ignore_index=True)
      if (i + 1) % read_message_size == 0:
        print("{i}件データフレームに読み込み完了".format(i=i+1))

    ldcc_df.index = ldcc_df.index + 1
    return ldcc_df

In [32]:
DATA_DIR = "./datasets/ldcc-20140209"
file_name = "kaden-channel"

read_file_csv = "kaden-channel_20200405003708.csv"
read_bk_csv = True

if read_bk_csv:
    register_documents = pd.read_csv(DATA_DIR + '/' +  read_file_csv, index_col=0)   
else:
    register_documents = load_ldcc_to_pd(DATA_DIR + '/' + file_name)
    # csvファイルに出力
    now = datetime.datetime.now().strftime('%Y%m%d%H%M%S')
    register_documents.to_csv(DATA_DIR + '/' + file_name + '_' + now + '.csv')

register_documents.head(3)

title  ...                                               text
1  Hulu、ついに待望のApple TVに対応！一周年記念で「Hulu アンバサダープロジェク...  ...  Hulu、ついに待望のApple TVに対応！一周年記念で「Hulu アンバサダープロジェク...
2                            【ニュース】電力使用量９日が８社管内で今夏最高  ...  【ニュース】電力使用量９日が８社管内で今夏最高気温が高い日が続く。特に９日は各地で気温が上が...
3           【ガイガーカウンター特集】これなら手が届く！2万円以下の家庭用放射線計測器大集合  ...  【ガイガーカウンター特集】これなら手が届く！2万円以下の家庭用放射線計測器大集合家電チャンネ...

[3 rows x 4 columns]

### ELMoで文書ベクトルを算出

In [48]:
DATA_DIR = "./datasets/ldcc-20140209"
file_name = "kaden-channel"
TEXT_COLUMN = "text"

read_file_pickle = "kaden-channel_20200405015516.pkl"
read_bk_pickle = True

if read_bk_pickle:
    with open(DATA_DIR + '/' + read_file_pickle, 'rb') as f_pkl:
       register_documents_vec = pickle.load(f_pkl)
else:
    register_documents_words_vec = predict_word_vec(elmo_model, register_documents[TEXT_COLUMN].values)
    register_documents_vec = calc_doc_vec(register_documents_words_vec)
    # pklファイルに出力
    now = datetime.datetime.now().strftime('%Y%m%d%H%M%S')
    export_pkl_file = DATA_DIR + '/' + file_name + '_' + now + '.pkl'
    with open(export_pkl_file, mode='wb') as f:
        pickle.dump(register_documents_vec, f)

print("文書ベクトルの次元数確認{shape}".format(shape=register_documents_vec.shape))

文書ベクトルの次元数確認(864, 1024)


### Indexを登録する特徴量空間の定義
検索アルゴリズムと必要な初期値はこちら参照<br>
https://github.com/facebookresearch/faiss/wiki/Faiss-indexes

In [0]:
# 登録するデータ1件分の次元数
vector_dim = register_documents_vec.shape[1]
# 分割する領域の数
voronoi_num = 20
# 検索時に含める近傍の領域の数
voronoi_near = 10

#### 高速な近似アルゴリズムIndeIVFFlatを使用
https://github.com/facebookresearch/faiss/wiki/Faster-search

In [0]:
quantizer = faiss.IndexFlatL2(vector_dim)
index = faiss.IndexIVFFlat(quantizer, vector_dim, voronoi_num)

### Indexへの追加（+ボロノイ領域の学習）

In [0]:
assert not index.is_trained
index.train(register_documents_vec)
assert index.is_trained

In [37]:
# idの付与
ids = np.arange(start=1, stop=register_documents_vec.shape[0]+1)
print("idsの長さ{size}".format(size=len(ids)))
ids[:5]

idsの長さ864


array([1, 2, 3, 4, 5])

In [0]:
index.add_with_ids(register_documents_vec, ids) 

#### 結果の保存

In [0]:
EXPORT_DIR = "./exports"
now = datetime.datetime.now().strftime('%Y%m%d%H%M%S')

In [0]:
faiss.write_index(index, EXPORT_DIR + "/features_" + now + ".index")

## 検索エンジンにクエリを投げてみる

#### 質問文の前処理

In [0]:
# 質問文
queries = ["新作のカメラに関する記事", "Macの新作", "コンピュータ", "Microsoftに関する記事"]

In [52]:
# ELMoで単語ベクトルに変換
queries_words_vec = predict_word_vec(elmo_model, queries)
# 文書ベクトルに変換
queries_vec = calc_doc_vec(queries_words_vec)
print("入力の次元{shape}".format(shape=queries_vec.shape))

2020-04-05 02:06:16,311 INFO: 1 batches, avg len: 11.8


実行時間:0:00:00.082174
実行時間:0:00:00.000594
入力の次元(4, 1024)


#### インデックスから類似文を検索する

In [0]:
@time_watch
def search_doc(queries_vec, search_doc_num, index):
    """
    類似文章の検索

    Parameters
    -----
    queries_vec : ndarray
    search_doc_num : int
        何件分まで検索してくるか
    index : index_obj
        faissのindexオブジェクト

    Returns
    -----
    D : D_obj
    I : I_obj
    """
    d, i = index.search(queries_vec, search_doc_num)
    return d, i

In [68]:
# 取得したい結果の件数を設定
search_doc_num = 15

results_distances, results_ids = search_doc(queries_vec, search_doc_num, index)

実行時間:0:00:00.000728


In [70]:
# 結果の描画
for i, (result_distances, result_ids) in enumerate(zip(results_distances, results_ids)):
    
    print("{i}番目の検索クエリ:{query}".format(i=i+1, query=queries[i]))
    print("-----検索結果-----")

    for j, (result_distance, result_id) in enumerate(zip(result_distances, result_ids)):
        if result_id != -1:
            print("第{j}位\t文書id:{id} 「{title}」 url:（{url}）"
            .format(j=j+1, id=result_id, title=register_documents["title"][result_id], url=register_documents["url"][result_id]))
            print("\t（距離{distance}）\t記事の内容{text}\n".format(distance=result_distance, text=register_documents["text"][result_id]))

    print("-----{i}番目の結果ここまで-----\n\n".format(i=i+1))

1番目の検索クエリ:新作のカメラに関する記事
-----検索結果-----
第1位	文書id:61 「パナソニックが新「エコナビ」キャンペーンを開始！ナビゲーターに吉瀬美智子さん」 url:（http://news.livedoor.com/article/detail/5841998/）
	（距離13.453042030334473）	記事の内容パナソニックが新「エコナビ」キャンペーンを開始！ナビゲーターに吉瀬美智子さんパナソニックは9月6日に開催した記者発表会で、家電がムダを見つけて節電をする「エコナビ」機能を普及する、新「エコナビ」キャンペーンを発表した。会場にはナビゲーターを務める女優の吉瀬美智子さんが登場した。パナソニックは、最適なエコを考え家電自らが節電する「エコナビ」を搭載した家電を2009年秋より発売している。今回スタートした新しいキャンペーンでは節電を頑張る人をテレビや新聞・雑誌等で応援するということだ。またすでに実施されていた「エコナビ塔載の植樹対象商品1台で、1本の植樹を！」キャンペーンも、対象商品を拡大して継続される。植樹については「子どもたちに、希望の桜を贈ろう！」をテーマに、東北をはじめとする小学校、幼稚園、保育園に、桜の苗木を贈るということだ。東日本大震災で被害を受けた被災地に桜の花が咲くことになる。ナビゲーターの吉瀬美智子さんは会場で、自身の行っていることとして「エアコンの温度設定を上げる」という身近な節電方法を話した。また、昨年末に結婚をしている吉瀬さんは「使わない電気を主人がつけっぱなしにしているときには、私が消しています」と結婚生活の様子も語った。エコナビ（パナソニック）■関連記事・食品の収納スペースアップで冷気の漏れを押さえるパナソニックのトップユニット冷蔵庫新発売・ハンガーに掛けたままスピード乾燥！シャープ、プラズマクラスター洗濯機がパワーアップ・【話題】地デジ化をきっかけに、テレビ離れが増加？・皇居ランのお供に！アディダスランベースがウォークマン無料貸し出しへ・パナソニック新発売のエアコンは新開発「トップユニット」構造の「Xシリーズ」

第2位	文書id:434 「子どもだけにはもったいない！トイストーリーの世界を体験できそうなカメラ付きミニカー【話題】」 url:（http://news.livedoor.com/art